### ISSUE TITLE
Intermediate features visualization

### ISSUE THREAD

**Issue by momopusheen** [Nithin-GK/MaxFusion#1]
Thanks for your brilliant work!

I've been trying to visualize the intermediate features of the UNet model using the textvariance.ipynb notebook, but it seems that the 'unet' model is not referenced in the provided code. Could you please take a look into this?

<img width="341" alt="image" src="https://github.com/Nithin-GK/MaxFusion/assets/110893264/52cd3dc4-ae1e-4069-96f1-754de9a04f14">

**Comment by Nithin-GK** [comment]
Hello,

Thank you for pointing out this issue. I have added the corresponding file.

**Comment by momopusheen** [comment]
Hi, thanks for your quick reply!

It seems _textvariance.ipynb_ notebook referenced 'ptp_utils_text', which is missing as well. Additionally, there's no environment.yaml. Could you please add these files?

**Comment by Nithin-GK** [comment]
Hello,

 Really sorry that I missed this message before. I added ptp_utils_text
